name: Update Attributions
permissions:
  contents: write
on:
  workflow_call:
    inputs:
      commit_message:
        type: string
  workflow_dispatch:
jobs:
  update-attributions:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      - run: git pull
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install cargo-attribution
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-attribution
      - name: Run cargo attribution
        run: cargo attribution
      - name: "Import GPG key"
        id: import-gpg
        uses: ./.github/workflows/setup_gpg.yaml
      - name: "Commit and push changes"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_author: "${{ steps.import-gpg.outputs.name }} <${{ steps.import-gpg.outputs.email }}>"
          commit_user_name: ${{ steps.import-gpg.outputs.name }}
          commit_user_email: ${{ steps.import-gpg.outputs.email }}
